print("Getting to know you")
print()
name = input("What is your name? ")
favourite_food = input("What is your favourite food? ")
favourite_music = input("What is your favourite music? ")
location = input("Where do you live? ")
print()
print("You are")
print(name)
print("You are probably hungry for")
print(favourite_food)
print("and you're definitely getting your groove on to")
print(favourite_music)
print("living in the amazing")
print(location)